### ISSUE TITLE
aframe-potree-loader-component.js:73 Fetch API cannot load file:///C:/aframe-potree-loader-component-master/examples/basic/pointclouds/cloud.js. URL scheme "file" is not supported.

### ISSUE THREAD

**Issue by MannyMeadows** [mattrei/aframe-potree-loader-component#2]
Works great on the supplied example datasets, however I get the below error when converting my own point cloud. Any ideas?

`aframe-potree-loader-component.js:73 Fetch API cannot load file:///C:/aframe-potree-loader-component-master/examples/basic/pointclouds/cloud.js. URL scheme "file" is not supported.`

Many thanks

**Comment by mattrei** [comment]
It's not possible to load local files within browsers. This would be a big security issue.
