### ISSUE TITLE
VR Controllers Render huge. (other scene objects rendered in point cloud buffer)

### ISSUE THREAD

**Issue by nrgapple** [mattrei/aframe-potree-loader-component#3]
View using a VR headset. Controllers are huge and warped. If you remove the potree entity they go back to normal.

https://glitch.com/edit/#!/potree

**Comment by nrgapple** [comment]
![org mozilla vrbrowser-20190807-221307](https://user-images.githubusercontent.com/10817537/62670938-fcc1be80-b962-11e9-8d17-d6eba6826778.jpg)

**Comment by nrgapple** [comment]
It looks like Potree is taking all objects in the scene and warping their rendering

**Comment by nrgapple** [comment]
Even the gizmos on scene entities in the inspector view are warped: 
![image](https://user-images.githubusercontent.com/10817537/62712622-30cfca80-b9c9-11e9-895b-cb13d3b99e2b.png)

**Comment by nrgapple** [comment]
This even happens in your example scene:
![image](https://user-images.githubusercontent.com/10817537/62713592-fcf5a480-b9ca-11e9-8168-1301d4a8422d.png)

**Comment by mattrei** [comment]
fixed in version 0.11.0
