### ISSUE TITLE
Large Scale Potree Position/Rotation

### ISSUE THREAD

**Issue by ktalexan** [mattrei/aframe-potree-loader-component#4]
Just curious if you could give a better explanation on setting up large scale landscapes for your loader with concern to position and rotation.

We have potions such as"-6080009.505 -2162050.336 -749.499" in a state plane coordinate system.

If you could share your workflow it would be a great help.

**Comment by mattrei** [comment]
I think you have to normalize the point cloud in an Pointcloud editor before so that is orientated and positioned at 0 0 0.
